In [90]:
import torch

In [91]:
x =torch.arange(24).reshape(2,3,4)

In [92]:
x.shape

torch.Size([2, 3, 4])

In [93]:
x[0]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [94]:
x[1]

tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])

In [95]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [96]:
x[:,1,:]

tensor([[ 4,  5,  6,  7],
        [16, 17, 18, 19]])

In [97]:
x[:, :, 0]

tensor([[ 0,  4,  8],
        [12, 16, 20]])

In [98]:
import torch

x = torch.arange(24).reshape(2, 3, 4)

print(x)
print("shape:", x.shape)
print("dtype:", x.dtype)
print("device:", x.device)
print("numel:", x.numel())
print("element size:", x.element_size())
print("memory:", x.numel() * x.element_size(), "bytes")

print("x[0]:", x[0])
print("x[0].shape:", x[0].shape)

print("x[:, 1, :]:", x[:, 1, :])
print("x[:, 1, :].shape:", x[:, 1, :].shape)

print("x[:, :, 0]:", x[:, :, 0])
print("x[:, :, 0].shape:", x[:, :, 0].shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
shape: torch.Size([2, 3, 4])
dtype: torch.int64
device: cpu
numel: 24
element size: 8
memory: 192 bytes
x[0]: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
x[0].shape: torch.Size([3, 4])
x[:, 1, :]: tensor([[ 4,  5,  6,  7],
        [16, 17, 18, 19]])
x[:, 1, :].shape: torch.Size([2, 4])
x[:, :, 0]: tensor([[ 0,  4,  8],
        [12, 16, 20]])
x[:, :, 0].shape: torch.Size([2, 3])


In [99]:
x = torch.randn(2, 8, 768)
# (batch,sequence_length,hidden_size)


In [100]:
x.shape

torch.Size([2, 8, 768])

In [101]:
x.numel()

12288

In [102]:
x.element_size()

4

In [103]:
x[0].shape

torch.Size([8, 768])

In [104]:
x[:, 0].shape

torch.Size([2, 768])

In [105]:
x[:,:,0].shape

torch.Size([2, 8])

In [106]:
x.reshape(2, 8, 12, 64).shape

torch.Size([2, 8, 12, 64])

In [107]:
y = x.reshape(2, 8, 12, 64)

In [108]:
z = y.transpose(1, 2)

In [109]:
z.shape

torch.Size([2, 12, 8, 64])

In [110]:
import torch

B = 1
H = 2
T = 4
D = 3

Q = torch.randn(B, H, T, D)
K = torch.randn(B, H, T, D)

print("Q:", Q.shape)
print("K:", K.shape)

scores = Q @ K.transpose(-2, -1)

print("K^T:", K.transpose(-2, -1).shape)
print("scores:", scores.shape)

Q: torch.Size([1, 2, 4, 3])
K: torch.Size([1, 2, 4, 3])
K^T: torch.Size([1, 2, 3, 4])
scores: torch.Size([1, 2, 4, 4])


In [111]:
import torch

Q = torch.tensor([[[[1., 2.],
                     [3., 4.]]]])

K = torch.tensor([[[[5., 6.],
                     [7., 8.]]]])

print("Q:", Q)
print("Q shape:", Q.shape)

print("K:", K)
print("K shape:", K.shape)

scores = Q @ K.transpose(-2, -1)

print("scores:", scores)
print("scores shape:", scores.shape)

Q: tensor([[[[1., 2.],
          [3., 4.]]]])
Q shape: torch.Size([1, 1, 2, 2])
K: tensor([[[[5., 6.],
          [7., 8.]]]])
K shape: torch.Size([1, 1, 2, 2])
scores: tensor([[[[17., 23.],
          [39., 53.]]]])
scores shape: torch.Size([1, 1, 2, 2])


In [112]:
scores

tensor([[[[17., 23.],
          [39., 53.]]]])

In [113]:
import torch

Q = torch.tensor([[[[1., 2.],
                     [3., 4.]]]])

K = torch.tensor([[[[5., 6.],
                     [7., 8.]]]])

scores = Q @ K.transpose(-2, -1)

print(scores)

tensor([[[[17., 23.],
          [39., 53.]]]])


In [114]:
import torch

Q = torch.tensor([[[[1., 2.],
                     [3., 4.],
                     [5.,6.]]]])

K = torch.tensor([[[[1., 1.],
                     [2., 2.],
                     [3.,3.]]]])

scores = Q @ K.transpose(-2, -1)

print(scores)

scale = torch.sqrt(torch.tensor(Q.shape[-1], dtype=Q.dtype))
scaled_scores = scores / scale
scaled_scores

tensor([[[[ 3.,  6.,  9.],
          [ 7., 14., 21.],
          [11., 22., 33.]]]])


tensor([[[[ 2.1213,  4.2426,  6.3640],
          [ 4.9497,  9.8995, 14.8492],
          [ 7.7782, 15.5563, 23.3345]]]])

In [115]:
import torch

Q= torch.tensor([[[[1,2],
                   [3,4],
                   [5,6]]]])

K = torch.tensor([[[[1,1],
                    [2,2],
                    [3,3]]]])

score = Q @ K.transpose(-2,-1)

score


scale = torch.sqrt(torch.tensor(Q.shape[-1], dtype=Q.dtype))
scaled_score =score/scale

print("scale:", scale)
print("scaled scores:", scaled_score)


scale: tensor(1.4142)
scaled scores: tensor([[[[ 2.1213,  4.2426,  6.3640],
          [ 4.9497,  9.8995, 14.8492],
          [ 7.7782, 15.5563, 23.3345]]]])


In [116]:
Q.shape

torch.Size([1, 1, 3, 2])

In [117]:
K.shape

torch.Size([1, 1, 3, 2])

In [118]:
score.shape

torch.Size([1, 1, 3, 3])

In [119]:
scores = Q @ K.transpose(1, 2)

RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [3, 2] but got: [3, 1].

In [120]:
mask = torch.tril(torch.ones(3,3))
masked_scores = scaled_scores.masked_fill(mask==0,float("-inf"))

print(masked_scores)

tensor([[[[ 2.1213,    -inf,    -inf],
          [ 4.9497,  9.8995,    -inf],
          [ 7.7782, 15.5563, 23.3345]]]])


In [121]:
import torch

Q= torch.tensor([[[[1,2],
      [3,4],
      [5,6]]]])

K = torch.tensor([[[[1,1],
       [2,2],
       [3,3]]]])

scores = Q @ K.transpose(-2,-1)

scale = torch.sqrt(torch.tensor(Q.shape[-1],dtype=Q.dtype))

scaled_scores =scores/scale

mask =torch.tril(torch.ones(3,3))

masked_scores = scaled_scores.masked_fill(mask ==0,float("-inf"))

mask
masked_scores

tensor([[[[ 2.1213,    -inf,    -inf],
          [ 4.9497,  9.8995,    -inf],
          [ 7.7782, 15.5563, 23.3345]]]])

In [122]:
import torch

Q= torch.tensor([[[[1,2],
      [3,4],
      [5,6]]]])

K = torch.tensor([[[[1,1],
       [2,2],
       [3,3]]]])

scores = Q @ K.transpose(-2,-1)

scale = torch.sqrt(torch.tensor(Q.shape[-1],dtype=Q.dtype))

scaled_scores =scores/scale

mask =torch.tril(torch.ones(3,3))

masked_scores = scaled_scores.masked_fill(mask ==0,float("-inf"))



In [123]:
attention_weights = torch.softmax(masked_scores, dim =-1)

print("attention weights:")
print(attention_weights)


print("row sums:")
print(attention_weights.sum(dim=-1))

attention weights:
tensor([[[[1.0000e+00, 0.0000e+00, 0.0000e+00],
          [7.0353e-03, 9.9296e-01, 0.0000e+00],
          [1.7530e-07, 4.1860e-04, 9.9958e-01]]]])
row sums:
tensor([[[1., 1., 1.]]])


In [124]:
V = torch.tensor([[[[10., 20.],
                     [30., 40.],
                     [50., 60.]]]])


attention_output = attention_weights @ V

print("V shape:", V.shape)
print("attention output:")
print(attention_output)
print("attention output shape:", attention_output.shape)

V shape: torch.Size([1, 1, 3, 2])
attention output:
tensor([[[[10.0000, 20.0000],
          [29.8593, 39.8593],
          [49.9916, 59.9916]]]])
attention output shape: torch.Size([1, 1, 3, 2])


In [125]:
#### Toy Attention
def causal_attention(Q,K,V):

    scores = Q @ K.transpose(-2,-1)

    scale = torch.sqrt(torch.tensor(Q.shape[-1],dtype=Q.dtype))

    scaled_score = scores/scale

    mask = torch.tril(torch.ones(Q.shape[-2],Q.shape[-2]))

    masked_scores = scaled_score.masked_fill(mask ==0,float("-inf"))

    attention_weights = torch.softmax(masked_scores,dim=-1)

    attention_output = attention_weights @ V

    return attention_output ,attention_weights

output, weights = causal_attention(Q, K, V)

print("output:")
print(output)

print("weights:")
print(weights)

print("row sums:")
print(weights.sum(dim=-1))

output:
tensor([[[[10.0000, 20.0000],
          [29.8593, 39.8593],
          [49.9916, 59.9916]]]])
weights:
tensor([[[[1.0000e+00, 0.0000e+00, 0.0000e+00],
          [7.0353e-03, 9.9296e-01, 0.0000e+00],
          [1.7530e-07, 4.1860e-04, 9.9958e-01]]]])
row sums:
tensor([[[1., 1., 1.]]])


In [126]:
linear =torch.nn.Linear(4,6)

linear

Linear(in_features=4, out_features=6, bias=True)

In [127]:
import torch

linear =torch.nn.Linear(4,6)

x =torch.randn(2,3,4)

y =linear(x)

print("x:",x.shape)
print("weight:",linear.weight.shape)
print("bias:", linear.bias.shape)
print("y:", y.shape)


x: torch.Size([2, 3, 4])
weight: torch.Size([6, 4])
bias: torch.Size([6])
y: torch.Size([2, 3, 6])


In [128]:
import torch

B =2
T =3
hidden =8

x = torch.randn(B,T,hidden)

qkv_projection = torch.nn.Linear(hidden,3 * hidden)

qkv =qkv_projection(x)

print("x:",x.shape)
print("qkv:",qkv.shape)

x: torch.Size([2, 3, 8])
qkv: torch.Size([2, 3, 24])


In [129]:
B =2
T=3
hidden =8

x =torch.randn(B,T,hidden)

qkv_projection = torch.nn.Linear(hidden, 3 * hidden)

qkv = qkv_projection(x)

Q,K,V = torch.chunk(qkv,chunks=3,dim=-1)

print(Q.shape,K.shape,V.shape)

torch.Size([2, 3, 8]) torch.Size([2, 3, 8]) torch.Size([2, 3, 8])


In [130]:
hidden =8
heads =2
head_dim =4


Q=Q.reshape(B,T,heads,head_dim)
K=K.reshape(B,T,heads,head_dim)
V=V.reshape(B,T,heads,head_dim)

In [131]:
print((Q.transpose(1,2).shape,K.transpose(1,2).shape,V.transpose(1,2).shape))

(torch.Size([2, 2, 3, 4]), torch.Size([2, 2, 3, 4]), torch.Size([2, 2, 3, 4]))


In [132]:
def causal_attention(Q,K,V,mask):

    scores = Q @ K.transpose(-2,-1)

    scale = torch.sqrt(torch.tensor(Q.shape[-1],dtype=Q.dtype))

    scaled_score = scores/scale

    mask = torch.tril(torch.ones(Q.shape[-2],Q.shape[-2]))

    masked_scores = scaled_score.masked_fill(mask ==0,float("-inf"))

    attention_weights = torch.softmax(masked_scores,dim=-1)

    attention_output = attention_weights @ V

    return attention_output , attention_weights

output= causal_attention(Q, K, V,mask)



In [133]:
output.shape

AttributeError: 'tuple' object has no attribute 'shape'

In [134]:
output.transpose(1,2)

output = output.reshape(B,T,hidden)

print(output.shape)

AttributeError: 'tuple' object has no attribute 'transpose'

In [ ]:
attention_output,weights = causal_attention(Q, K, V)

print("attention:", attention_output.shape)

attention_output = attention_output.transpose(1, 2)

print("after transpose:", attention_output.shape)

attention_output = attention_output.reshape(B, T, hidden)

print("after reshape:", attention_output.shape)


TypeError: causal_attention() missing 1 required positional argument: 'mask'

In [135]:
import torch
import torch.nn as nn 

class MultiHeadAttention(nn.Module):

    def __init__(self,hidden,heads,max_seq_len):
        super().__init__()

        self.hidden = hidden
        self.heads = heads
        self.head_dim =hidden //heads

        self.register_buffer("causal_mask",torch.tril(torch.ones(max_seq_len,max_seq_len)))

        self.qkv_projection = nn.Linear(hidden,3 * hidden)
        self.output_projection =nn.Linear(hidden,hidden)



    def forward(self,x):
        B,T,C = x.shape


        qkv =self.qkv_projection(x)

        Q,K,V = torch.chunk(qkv,chunks=3,dim =-1)

        Q =Q.reshape(B,T,self.heads,self.head_dim)
        K =K.reshape(B,T,self.heads,self.head_dim)
        V =V.reshape(B,T,self.heads,self.head_dim)

        Q = Q.transpose(2,1)
        K =K.transpose(2,1)
        V =V.transpose(2,1)

        mask_slice = self.causal_mask[:T, :T]

        attention_output, _ = causal_attention(Q,K,V,mask_slice)

        attention_output =attention_output.transpose(2,1)

        attention_output =attention_output.reshape(B,T,C)

        output =self.output_projection(attention_output)

        return output





In [136]:
attention = MultiHeadAttention(
    hidden=8,
    heads=2
)

x = torch.randn(2, 3, 8)

y = attention(x)

print("x:", x.shape)
print("y:", y.shape)

TypeError: MultiHeadAttention.__init__() missing 1 required positional argument: 'max_seq_len'

In [137]:
print(sum(p.numel() for p in attention.parameters()))

288


In [138]:
attention = MultiHeadAttention(
    hidden=8,
    heads=2,
    max_seq_len=16
)

x = torch.randn(2, 3, 8)

y = attention(x)

print(y.shape)
print(attention.causal_mask.shape)
print(attention.causal_mask.device)

torch.Size([2, 3, 8])
torch.Size([16, 16])
cpu


In [139]:
print(
    "parameters:",
    sum(p.numel() for p in attention.parameters())
)

print(
    "buffers:",
    [(name, buf.shape) for name, buf in attention.named_buffers()]
)

parameters: 288
buffers: [('causal_mask', torch.Size([16, 16]))]


In [140]:
attention = attention.to("cuda")

print(attention.causal_mask.device)

cuda:0


# LayerNorm

In [141]:
x =torch.tensor([2.0,4.,6.,8.])

ln = nn.LayerNorm(4)

y =ln(x)

print("x:",x)
print("y:",y)
print("weight:",ln.weight)
print("bias:",ln.bias)

x: tensor([2., 4., 6., 8.])
y: tensor([-1.3416, -0.4472,  0.4472,  1.3416],
       grad_fn=<NativeLayerNormBackward0>)
weight: Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)
bias: Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)


In [142]:
x = torch.tensor([[2., 4., 6., 8.]])

mean = torch.mean(x)
variance =  torch.var(x)

eps =1e-5
x_norm = (x -mean)/torch.sqrt(variance +eps)

print(mean,variance,x_norm)

tensor(5.) tensor(6.6667) tensor([[-1.1619, -0.3873,  0.3873,  1.1619]])


In [143]:
nn.LayerNorm(4)(x)

tensor([[-1.3416, -0.4472,  0.4472,  1.3416]],
       grad_fn=<NativeLayerNormBackward0>)

In [144]:
import torch
import torch.nn as nn

x = torch.tensor([[2., 4., 6., 8.]])

ln = nn.LayerNorm(4)

print("weight:", ln.weight)
print("bias:", ln.bias)

y = ln(x)

print("y:", y)

weight: Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)
bias: Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)
y: tensor([[-1.3416, -0.4472,  0.4472,  1.3416]],
       grad_fn=<NativeLayerNormBackward0>)


In [145]:
class MyLayerNorm(nn.Module):

    def __init__(self,hidden_size,eps =1e-5):

        super().__init__()

        self.eps =eps

        self.weight = nn.Parameter(torch.ones(hidden_size))

        self.bias =nn.Parameter(torch.zeros(hidden_size))

    def forward(self, x):

        mean = torch.mean(x, dim=-1, keepdim=True)

        variance = torch.mean((x - mean) ** 2, dim=-1, keepdim=True)

        x_norm = (x - mean) / torch.sqrt(variance + self.eps)

        return x_norm * self.weight + self.bias



In [146]:
torch.manual_seed(42)

x = torch.randn(2, 8, 768)

my_ln = MyLayerNorm(768)
torch_ln = nn.LayerNorm(768)

# Make both have exactly the same parameters
torch_ln.weight.data.copy_(my_ln.weight.data)
torch_ln.bias.data.copy_(my_ln.bias.data)

y_my = my_ln(x)
y_torch = torch_ln(x)

print("My shape:", y_my.shape)
print("PyTorch shape:", y_torch.shape)

print("Max difference:", torch.max(torch.abs(y_my - y_torch)))
print("Match:", torch.allclose(y_my, y_torch))

My shape: torch.Size([2, 8, 768])
PyTorch shape: torch.Size([2, 8, 768])
Max difference: tensor(4.7684e-07, grad_fn=<MaxBackward1>)
Match: False


In [147]:
class MLP(nn.Module):
    def __init__(self, hidden_size):
        
        super().__init__()

        self.fc1 = nn.Linear(hidden_size, 4 * hidden_size)
        self.gelu = nn.GELU(approximate="tanh")
        self.fc2 = nn.Linear(4 * hidden_size, hidden_size)

    def forward(self, x):
        x = self.fc1(x)
        x = self.gelu(x)
        x = self.fc2(x)
        return x

In [148]:
x = torch.randn(2, 8, 768)

mlp = MLP(768)

y = mlp(x)

print("input:", x.shape)
print("output:", y.shape)

input: torch.Size([2, 8, 768])
output: torch.Size([2, 8, 768])


In [149]:
import torch
import torch.nn as nn


class MLP(nn.Module):

    def __init__(self, hidden_size):
        super().__init__()

        # 768 → 3072
        self.fc1 = nn.Linear(hidden_size, 4 * hidden_size)

        self.gelu = nn.GELU(approximate="tanh")

        # 3072 → 768
        self.fc2 = nn.Linear(4 * hidden_size, hidden_size)

    def forward(self, x):

        x = self.fc1(x)


        x = self.gelu(x)

        x = self.fc2(x)

        return x


# Test
x = torch.randn(2, 8, 768)

mlp = MLP(768)

y = mlp(x)

print("input:", x.shape)
print("output:", y.shape)

print("fc1 weight:", mlp.fc1.weight.shape)
print("fc2 weight:", mlp.fc2.weight.shape)

print("parameters:",
      sum(p.numel() for p in mlp.parameters()))

input: torch.Size([2, 8, 768])
output: torch.Size([2, 8, 768])
fc1 weight: torch.Size([3072, 768])
fc2 weight: torch.Size([768, 3072])
parameters: 4722432


In [150]:
for name, p in mlp.named_parameters():
    print(name, p.shape, p.numel())

print("total:", sum(p.numel() for p in mlp.parameters()))

fc1.weight torch.Size([3072, 768]) 2359296
fc1.bias torch.Size([3072]) 3072
fc2.weight torch.Size([768, 3072]) 2359296
fc2.bias torch.Size([768]) 768
total: 4722432


In [151]:
import torch
import torch.nn as nn

class GPT2Block(nn.Module):

    def __init__(self, hidden_size, num_heads, max_seq_len):
        super().__init__()

        self.ln1 = MyLayerNorm(hidden_size)

        self.attention = MultiHeadAttention(hidden_size, num_heads, max_seq_len)
  
        self.ln2 = MyLayerNorm(hidden_size)
  
        self.mlp = MLP(hidden_size)

    def forward(self, x):
        
        residual = x
        
        x = self.ln1(x)
        x = self.attention(x)
        
        x = residual + x

        residual = x
    
        x = self.ln2(x)
        x = self.mlp(x)
        x = residual + x

        return x


In [152]:
x = torch.randn(2, 8, 768)

block = GPT2Block(
    hidden_size=768,
    num_heads=12,
    max_seq_len=16
)

y = block(x)

print("input:", x.shape)
print("output:", y.shape)
print("input mean:", x.mean().item())
print("output mean:", y.mean().item())
print("input std:", x.std().item())
print("output std:", y.std().item())

input: torch.Size([2, 8, 768])
output: torch.Size([2, 8, 768])
input mean: -0.002498344285413623
output mean: 0.002135833725333214
input std: 0.9955921769142151
output std: 1.0341339111328125


# EMbeddings

In [153]:
input_ids =torch.tensor([15496,995,0])

In [154]:
class GPT2Embeddings(nn.Module):

    def __init__(self, vocab_size, hidden_size, max_seq_len):
        super().__init__()

        self.token_embedding = nn.Embedding(vocab_size,hidden_size)

        self.position_embedding = nn.Embedding(max_seq_len,hidden_size)

    def forward(self, input_ids):

        # input_ids [B,T] 

        token_emb = self.token_embedding(input_ids)

        # Create positions 0,1,2,...,T-1

        positions = torch.arange(0,input_ids.shape[-1],device=input_ids.device)
        

        position_emb = self.position_embedding(positions)

        return token_emb + position_emb

In [155]:
positions.shape

NameError: name 'positions' is not defined

In [ ]:
emb = GPT2Embeddings(
    vocab_size=50257,
    hidden_size=768,
    max_seq_len=1024
)

input_ids = torch.tensor([
    [15496, 995, 0, 42]
])

x = emb(input_ids)

print(x.shape)


torch.Size([1, 4, 768])


                 input_ids [B,T]
                       │
                       ▼
                GPT2Embeddings
                       │
                       ▼
                   [B,T,768]
                       │
             ┌─────────▼─────────┐
             │                   │
             ▼                   │
          Block 1                │
             │                   │
             ▼                   │
          Block 2                │
             │                   │
            ...                  │
             │                   │
             ▼                   │
         Block 12                │
             │                   │
             ▼                   │
         LayerNorm               │
             │                   │
             ▼                   │
          [B,T,768]              │
             │                   │
             ▼                   │
       Linear → 50257            │
             │                   │
             ▼                   │
       logits [B,T,50257] ◄──────┘

In [ ]:
class GPT2(nn.Module):

    def __init__(self, vocab_size, hidden_size,
                 num_layers, num_heads, max_seq_len):

        super().__init__()

        self.embeddings = GPT2Embeddings(vocab_size,hidden_size,max_seq_len)

        self.blocks = nn.ModuleList([
            GPT2Block(hidden_size, num_heads, max_seq_len) 
            for _ in range(num_layers)
        ])

        self.ln_f = MyLayerNorm(hidden_size)

        self.lm_head = nn.Linear(hidden_size,vocab_size,bias=False)

    def forward(self, input_ids):

        x = self.embeddings(input_ids)


        for block in self.blocks:
            x = block(x)

        x = self.ln_f(x)

        logits = x @ self.embeddings.token_embedding.weight.T

        return logits

In [ ]:
model = GPT2(
    vocab_size=50257,
    hidden_size=768,
    num_layers=12,
    num_heads=12,
    max_seq_len=1024
)

input_ids = torch.tensor([
    [15496, 995, 0, 42]
])

logits = model(input_ids)

print("input:", input_ids.shape)
print("logits:", logits.shape)
print("parameters:", sum(p.numel() for p in model.parameters()))

NameError: name 'MyLayerNorm' is not defined

In [ ]:
class GPT2(nn.Module):

    def __init__(self, vocab_size, hidden_size,
                 num_layers, num_heads, max_seq_len):

        super().__init__()

        self.embeddings = GPT2Embeddings(vocab_size,hidden_size,max_seq_len)

        self.blocks = nn.ModuleList([
            GPT2Block(hidden_size, num_heads, max_seq_len) 
            for _ in range(num_layers)
        ])

        self.ln_f = MyLayerNorm(hidden_size)


    def forward(self, input_ids):

        x = self.embeddings(input_ids)


        for block in self.blocks:
            x = block(x)

        x = self.ln_f(x)

        logits = x @ self.embeddings.token_embedding.weight.T

        return logits

In [ ]:
model = GPT2(
    vocab_size=50257,
    hidden_size=768,
    num_layers=12,
    num_heads=12,
    max_seq_len=1024
)

input_ids = torch.tensor([
    [15496, 995, 0, 42]
])

logits = model(input_ids)

print("input:", input_ids.shape)
print("logits:", logits.shape)
print("parameters:", sum(p.numel() for p in model.parameters()))

input: torch.Size([1, 4])
logits: torch.Size([1, 4, 50257])
parameters: 124439808


__init__

    embeddings
        ↓
    GPT2Embeddings(...)

    blocks
        ↓
    ModuleList
        ├── GPT2Block
        ├── GPT2Block
        ├── GPT2Block
        ├── ...
        └── GPT2Block

    final LayerNorm
        ↓
    MyLayerNorm(...)

    language model head
        ↓
    Linear(768 → vocab_size)

input_ids
    ↓
embeddings
    ↓
for each block:
    x = block(x)
    ↓
final LayerNorm
    ↓
lm_head
    ↓
logits

In [ ]:
print(sum(p.numel() for p in model.parameters()))

124439808


input_ids
[B,T]
  │
  ▼
Token + Position Embeddings
  │
  ▼
[B,T,768]
  │
  ▼
Block 1
  │
  ▼
Block 2
  │
 ...
  │
  ▼
Block 12
  │
  ▼
Final LayerNorm
  │
  ▼
[B,T,768]
  │
  ▼
LM Head
  │
  ▼
[B,T,50257]

In [ ]:
print(model.embeddings.token_embedding.weight.shape)
print(model.embeddings.position_embedding.weight.shape)

for i, block in enumerate(model.blocks):
    print(
        i,
        block.ln1.weight.shape,
        block.attention.qkv_projection.weight.shape,
        block.attention.output_projection.weight.shape,
        block.ln2.weight.shape,
        block.mlp.fc1.weight.shape,
        block.mlp.fc2.weight.shape,
    )

print(model.ln_f.weight.shape)

torch.Size([50257, 768])
torch.Size([1024, 768])
0 torch.Size([768]) torch.Size([2304, 768]) torch.Size([768, 768]) torch.Size([768]) torch.Size([3072, 768]) torch.Size([768, 3072])
1 torch.Size([768]) torch.Size([2304, 768]) torch.Size([768, 768]) torch.Size([768]) torch.Size([3072, 768]) torch.Size([768, 3072])
2 torch.Size([768]) torch.Size([2304, 768]) torch.Size([768, 768]) torch.Size([768]) torch.Size([3072, 768]) torch.Size([768, 3072])
3 torch.Size([768]) torch.Size([2304, 768]) torch.Size([768, 768]) torch.Size([768]) torch.Size([3072, 768]) torch.Size([768, 3072])
4 torch.Size([768]) torch.Size([2304, 768]) torch.Size([768, 768]) torch.Size([768]) torch.Size([3072, 768]) torch.Size([768, 3072])
5 torch.Size([768]) torch.Size([2304, 768]) torch.Size([768, 768]) torch.Size([768]) torch.Size([3072, 768]) torch.Size([768, 3072])
6 torch.Size([768]) torch.Size([2304, 768]) torch.Size([768, 768]) torch.Size([768]) torch.Size([3072, 768]) torch.Size([768, 3072])
7 torch.Size([768]) 

# Comparison Between our GPT and HF's GPT 

In [ ]:
import torch
from transformers import GPT2LMHeadModel, GPT2Tokenizer

hf_model = GPT2LMHeadModel.from_pretrained("gpt2")
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

hf_model.eval()

ModuleNotFoundError: No module named 'transformers'

In [156]:
for name, param in hf_model.transformer.h[0].named_parameters():
    print(name, param.shape)

NameError: name 'hf_model' is not defined

In [157]:
@torch.no_grad()
def load_gpt2_weights(custom_model, hf_model):

    # embeddings
    custom_model.embeddings.token_embedding.weight.copy_(
        hf_model.transformer.wte.weight
    )

    custom_model.embeddings.position_embedding.weight.copy_(
        hf_model.transformer.wpe.weight
    )

    # transformer blocks
    for custom_block, hf_block in zip(
        custom_model.blocks,
        hf_model.transformer.h
    ):
        # LayerNorm 1
        custom_block.ln1.weight.copy_(hf_block.ln_1.weight)
        custom_block.ln1.bias.copy_(hf_block.ln_1.bias)

        # Attention QKV
        custom_block.attention.qkv_projection.weight.copy_(
            hf_block.attn.c_attn.weight.T
        )
        custom_block.attention.qkv_projection.bias.copy_(
            hf_block.attn.c_attn.bias
        )

        # Attention output projection
        custom_block.attention.output_projection.weight.copy_(
            hf_block.attn.c_proj.weight.T
        )
        custom_block.attention.output_projection.bias.copy_(
            hf_block.attn.c_proj.bias
        )

        # LayerNorm 2
        custom_block.ln2.weight.copy_(hf_block.ln_2.weight)
        custom_block.ln2.bias.copy_(hf_block.ln_2.bias)

        # MLP
        custom_block.mlp.fc1.weight.copy_(
            hf_block.mlp.c_fc.weight.T
        )
        custom_block.mlp.fc1.bias.copy_(
            hf_block.mlp.c_fc.bias
        )

        custom_block.mlp.fc2.weight.copy_(
            hf_block.mlp.c_proj.weight.T
        )
        custom_block.mlp.fc2.bias.copy_(
            hf_block.mlp.c_proj.bias
        )

    # final LayerNorm
    custom_model.ln_f.weight.copy_(
        hf_model.transformer.ln_f.weight
    )
    custom_model.ln_f.bias.copy_(
        hf_model.transformer.ln_f.bias
    )

In [158]:
custom_model = GPT2(
    vocab_size=50257,
    hidden_size=768,
    num_layers=12,
    num_heads=12,
    max_seq_len=1024,
)

custom_model.eval()

load_gpt2_weights(custom_model, hf_model)

NameError: name 'hf_model' is not defined

In [ ]:
text = "The future of AI inference is"

inputs = tokenizer(text, return_tensors="pt")

input_ids = inputs["input_ids"]

print(input_ids.shape)
print(input_ids)

torch.Size([1, 6])
tensor([[  464,  2003,   286,  9552, 32278,   318]])


In [ ]:
with torch.no_grad():
    hf_logits = hf_model(input_ids).logits
    custom_logits = custom_model(input_ids)

print(hf_logits.shape)
print(custom_logits.shape)

torch.Size([1, 6, 50257])
torch.Size([1, 6, 50257])


In [ ]:
print(torch.allclose(
    hf_logits,
    custom_logits,
    atol=1e-4,
    rtol=1e-4
))

NameError: name 'hf_logits' is not defined

In [ ]:
max_diff = torch.max(
    torch.abs(hf_logits - custom_logits)
)

print("max difference:", max_diff.item())

NameError: name 'hf_logits' is not defined

In [ ]:
hf_next_token = torch.argmax(hf_logits[:, -1, :], dim=-1)
custom_next_token = torch.argmax(custom_logits[:, -1, :], dim=-1)

print("HF:", hf_next_token)
print("Custom:", custom_next_token)

print(
    "same token:",
    torch.equal(hf_next_token, custom_next_token)
)

NameError: name 'hf_logits' is not defined

In [ ]:
hf_outputs = {}
custom_outputs = {}

def save_output(storage, name):
    def hook(module, inputs, output):
        hf_or_custom_output = output[0] if isinstance(output, tuple) else output
        storage[name] = hf_or_custom_output.detach()
    return hook

handles = []

for i in range(12):
    handles.append(
        hf_model.transformer.h[i].register_forward_hook(
            save_output(hf_outputs, f"block_{i}")
        )
    )

    handles.append(
        custom_model.blocks[i].register_forward_hook(
            save_output(custom_outputs, f"block_{i}")
        )
    )

with torch.no_grad():
    hf_logits = hf_model(input_ids).logits
    custom_logits = custom_model(input_ids)

for handle in handles:
    handle.remove()

for i in range(12):
    diff = (
        hf_outputs[f"block_{i}"]
        - custom_outputs[f"block_{i}"]
    ).abs().max().item()

    print(f"Block {i:2d}: max diff = {diff:.8f}")

print(
    "Final logits:",
    (hf_logits - custom_logits).abs().max().item()
)

NameError: name 'hf_model' is not defined

In [ ]:
hf_model.eval()
custom_model.eval()

NameError: name 'hf_model' is not defined

In [ ]:
with torch.no_grad():
    hf_logits = hf_model(input_ids).logits
    custom_logits = custom_model(input_ids)

print(torch.allclose(
    hf_logits,
    custom_logits,
    atol=1e-4,
    rtol=1e-4
))

print(
    "max difference:",
    (hf_logits - custom_logits).abs().max().item()
)

NameError: name 'hf_model' is not defined

# KV CACHE

In [ ]:
import torch

# Tensor 1 shape: [Batch=1, Time=2, Features=3]
t1 = torch.tensor([[[1, 2, 3],
                    [4, 5, 6]]])

# Tensor 2 shape: [Batch=1, Time=2, Features=2]
t2 = torch.tensor([[[7, 8],
                    [9, 10]]])

# Glue them together along the 3rd dimension (dim=2)
output = torch.cat([t1, t2], dim=2)

print("Output shape:", output.shape)  # Output: torch.Size([1, 2, 5])
print("\nOutput Values:\n", output)


Output shape: torch.Size([1, 2, 5])

Output Values:
 tensor([[[ 1,  2,  3,  7,  8],
         [ 4,  5,  6,  9, 10]]])


In [ ]:
import torch
import torch.nn as nn 

class MultiHeadAttention(nn.Module):

    def __init__(self,hidden,heads,max_seq_len):
        super().__init__()

        self.hidden = hidden
        self.heads = heads
        self.head_dim =hidden //heads

        self.register_buffer("causal_mask",torch.tril(torch.ones(max_seq_len,max_seq_len)))

        self.qkv_projection = nn.Linear(hidden,3 * hidden)
        self.output_projection =nn.Linear(hidden,hidden)



    def forward(self,x,past_kv=None):
        B,T,C = x.shape


        qkv =self.qkv_projection(x)

        Q,K,V = torch.chunk(qkv,chunks=3,dim =-1)

        Q =Q.reshape(B,T,self.heads,self.head_dim)
        K =K.reshape(B,T,self.heads,self.head_dim)
        V =V.reshape(B,T,self.heads,self.head_dim)

        Q = Q.transpose(1,2)
        K =K.transpose(1,2)
        V =V.transpose(1,2)

        if past_kv is not None:
            past_K, past_V = past_kv

            K= torch.cat([past_K, K], dim=2)
            V = torch.cat([past_V, V], dim=2)

        new_kv = (K, V)

        scores = Q @ K.transpose(-2, -1)

        scores = scores / (self.head_dim ** 0.5)

        attention_weights = torch.softmax(
            scores,
            dim=-1
        )

        attention_output = attention_weights @ V

        # [B,H,T,D] -> [B,T,H,D]
        attention_output = attention_output.transpose(1, 2)

        # [B,T,H,D] -> [B,T,C]
        attention_output = attention_output.reshape(
            B, T, C
        )

        output = self.output_projection(
            attention_output
        )

        return output, new_kv





## KV Cache: The Key Shape Change During Decoding

### Without KV Cache

```text
Q = [B, H, T, D]
K = [B, H, T, D]

        ↓  Q @ Kᵀ

scores = [B, H, T, T]

### With KV Cache
```text
Q = [B, H, 1, D]
K = [B, H, T, D]

        ↓  Q @ Kᵀ

scores = [B, H, 1, T]

```text
Previous tokens
     │
     ├── K₁ ─┐
     ├── K₂  │
     ├── K₃  │
     ├── ... │──→ KV Cache
     └── Kₜ ─┘

New token
     │
     └── Qₜ₊₁
          │
          ↓
    Qₜ₊₁ @ K_cacheᵀ
          │
          ↓
    [B,H,1,T+1]

In [ ]:
print("Q:", Q.shape)
print("K:", K.shape)
print("V:", V.shape)

Q: torch.Size([1, 1, 3, 2])
K: torch.Size([1, 1, 3, 2])


NameError: name 'V' is not defined

In [ ]:
attention = MultiHeadAttention(
    hidden=8,
    heads=2,
    max_seq_len=16
)

In [ ]:
x = torch.randn(1, 4, 8)

output, kv = attention(x)

print("output:", output.shape)
print("cached K:", kv[0].shape)
print("cached V:", kv[1].shape)

output: torch.Size([1, 4, 8])
cached K: torch.Size([1, 2, 4, 4])
cached V: torch.Size([1, 2, 4, 4])


In [ ]:
attention = MultiHeadAttention(
    hidden=8,
    heads=2,
    max_seq_len=16
)

x = torch.randn(1, 4, 8)

print("INPUT:", x.shape)

output, kv = attention(x)

print("OUTPUT:", output.shape)
print("CACHE K:", kv[0].shape)
print("CACHE V:", kv[1].shape)

INPUT: torch.Size([1, 4, 8])
OUTPUT: torch.Size([1, 4, 8])
CACHE K: torch.Size([1, 2, 4, 4])
CACHE V: torch.Size([1, 2, 4, 4])


In [ ]:
Q = Q.transpose(2, 1)
K = K.transpose(2, 1)
V = V.transpose(2, 1)

print("Q:", Q.shape)
print("K:", K.shape)
print("V:", V.shape)

NameError: name 'V' is not defined

In [ ]:
x_new = torch.randn(1, 1, 8)

output2, kv2 = attention(
    x_new,
    past_kv=kv
)

print("NEW INPUT:", x_new.shape)
print("OUTPUT 2:", output2.shape)
print("CACHE K 2:", kv2[0].shape)
print("CACHE V 2:", kv2[1].shape)

NEW INPUT: torch.Size([1, 1, 8])
OUTPUT 2: torch.Size([1, 1, 8])
CACHE K 2: torch.Size([1, 2, 5, 4])
CACHE V 2: torch.Size([1, 2, 5, 4])


In [ ]:
class kvcache():

    def __init__(self):
        self.k =None
        self.v = None

    def append(self,new_k,new_v):
        if self.k is None:

            self.k =new_k
            self.v =new_v

        else:
            self.k = torch.cat([self.k,new_k],dim =2)
            self.v =torch.cat([self.v,new_v],dim =2)

    def get(self):
        return self.k,self.v

In [ ]:
import torch

class PreallocatedKVCache:
    def __init__(self, batch_size, num_heads, max_seq_len, head_dim):
        self.batch_size = batch_size
        self.num_heads = num_heads
        self.max_seq_len = max_seq_len
        self.head_dim = head_dim

        self.k_cache = torch.zeros((batch_size, num_heads, max_seq_len, head_dim))
        self.v_cache = torch.zeros((batch_size, num_heads, max_seq_len, head_dim))

        # FIXED: This is our master length counter
        self.current_len = 0

    def update(self, new_k, new_v):
        new_len = new_k.shape[2]
        start_idx = self.current_len
        end_idx = start_idx + new_len

        if end_idx > self.max_seq_len:
            raise ValueError(f"Cache capacity exceeded! Max is {self.max_seq_len}, attempting to write up to {end_idx}")

        # Direct Slot Overwrite into pre-allocated memory slices
        self.k_cache[:, :, start_idx:end_idx, :] = new_k
        self.v_cache[:, :, start_idx:end_idx, :] = new_v
        
        # FIXED: Update our master length counter variable accurately
        self.current_len = end_idx
        
        # Use our clean get method to return zero-allocation pointer slices
        return self.get()

    def get(self):
        # FIXED: Use self.current_len to slice out the active populated blocks cleanly
        keys_view = self.k_cache[:, :, :self.current_len, :]
        values_view = self.v_cache[:, :, :self.current_len, :]
        
        return keys_view, values_view


In [ ]:
cache =PreallocatedKVCache(batch_size = 1,
num_heads = 2,
max_seq_len = 5,
head_dim = 4)

In [ ]:
print(cache.k_cache.shape)
print(cache.current_len)

K, V = cache.get()
print(K.shape)

torch.Size([1, 2, 5, 4])
0
torch.Size([1, 2, 0, 4])


In [ ]:
new_k = torch.tensor([[[[1., 2., 3., 4.]],
                       [[5., 6., 7., 8.]]]])

new_v = torch.tensor([[[[10., 20., 30., 40.]],
                       [[50., 60., 70., 80.]]]])

In [ ]:
K, V = cache.update(new_k, new_v)

print("storage:", cache.k_cache.shape)
print("current_len:", cache.current_len)
print("valid K:", K.shape)
print(K)

storage: torch.Size([1, 2, 5, 4])
current_len: 1
valid K: torch.Size([1, 2, 1, 4])
tensor([[[[1., 2., 3., 4.]],

         [[5., 6., 7., 8.]]]])


In [159]:
new_k2 = torch.tensor([[[[13., 22., 35., 44.]],
                       [[95., 896., 77., 48.]]]])

new_v2 = torch.tensor([[[[10., 20., 30., 40.]],
                       [[50., 60., 70., 80.]]]])

In [160]:
K, V = cache.update(new_k2, new_v2)

print("storage:", cache.k_cache.shape)
print("current_len:", cache.current_len)
print("valid K:", K.shape)
print(K)

storage: torch.Size([1, 2, 16, 4])
current_len: 5
valid K: torch.Size([1, 2, 5, 4])
tensor([[[[-2.5647e-01, -3.6573e-01, -4.5236e-02, -1.5130e+00],
          [ 9.2389e-02, -3.1856e-01, -2.1515e-01, -7.7037e-01],
          [ 2.8713e-01, -3.7822e-01,  1.6035e+00,  4.4850e-01],
          [ 1.6583e-01, -8.4052e-01,  1.3160e+00,  8.0230e-02],
          [ 1.3000e+01,  2.2000e+01,  3.5000e+01,  4.4000e+01]],

         [[-1.8849e-01, -1.1281e+00, -9.0688e-01, -1.6962e-01],
          [-3.4891e-01, -6.4959e-01, -4.7486e-03, -2.7183e-01],
          [ 1.2692e+00,  9.4277e-02, -5.5578e-01,  4.1650e-01],
          [ 7.6629e-01,  6.8781e-02, -1.0541e+00,  9.3358e-01],
          [ 9.5000e+01,  8.9600e+02,  7.7000e+01,  4.8000e+01]]]],
       grad_fn=<SliceBackward0>)


In [161]:
print(K.untyped_storage().data_ptr() == cache.k_cache.untyped_storage().data_ptr())

True


In [162]:
print(cache.k_cache.shape)
print(cache.current_len)

K, V = cache.get()
K[:, :, 0, :] = 999
print(cache.k_cache[:, :, 0, :])

torch.Size([1, 2, 16, 4])
5
tensor([[[999., 999., 999., 999.],
         [999., 999., 999., 999.]]], grad_fn=<SelectBackward0>)


In [163]:
new_k3 = torch.tensor([[[[13., 22., 35., 44.]],
                       [[95., 896., 77., 48.]]]])

new_v3 = torch.tensor([[[[130., 520., 360., 490.]],
                       [[504., 670., 750., 890.]]]])


K, V = cache.update(new_k2, new_v2)

print("storage:", cache.k_cache.shape)
print("current_len:", cache.current_len)
print("valid K:", K.shape)
print(K)

storage: torch.Size([1, 2, 16, 4])
current_len: 6
valid K: torch.Size([1, 2, 6, 4])
tensor([[[[ 9.9900e+02,  9.9900e+02,  9.9900e+02,  9.9900e+02],
          [ 9.2389e-02, -3.1856e-01, -2.1515e-01, -7.7037e-01],
          [ 2.8713e-01, -3.7822e-01,  1.6035e+00,  4.4850e-01],
          [ 1.6583e-01, -8.4052e-01,  1.3160e+00,  8.0230e-02],
          [ 1.3000e+01,  2.2000e+01,  3.5000e+01,  4.4000e+01],
          [ 1.3000e+01,  2.2000e+01,  3.5000e+01,  4.4000e+01]],

         [[ 9.9900e+02,  9.9900e+02,  9.9900e+02,  9.9900e+02],
          [-3.4891e-01, -6.4959e-01, -4.7486e-03, -2.7183e-01],
          [ 1.2692e+00,  9.4277e-02, -5.5578e-01,  4.1650e-01],
          [ 7.6629e-01,  6.8781e-02, -1.0541e+00,  9.3358e-01],
          [ 9.5000e+01,  8.9600e+02,  7.7000e+01,  4.8000e+01],
          [ 9.5000e+01,  8.9600e+02,  7.7000e+01,  4.8000e+01]]]],
       grad_fn=<SliceBackward0>)


In [164]:
import torch
import torch.nn as nn 

class MultiHeadAttention(nn.Module):

    def __init__(self, hidden, heads, max_seq_len):
        super().__init__()

        self.hidden = hidden
        self.heads = heads
        self.head_dim = hidden // heads

        self.register_buffer("causal_mask", torch.tril(torch.ones(max_seq_len, max_seq_len)))

        self.qkv_projection = nn.Linear(hidden, 3 * hidden)
        self.output_projection = nn.Linear(hidden, hidden)

    def forward(self, x, past_kv=None):
        B, T, C = x.shape

        qkv = self.qkv_projection(x)
        Q, K, V = torch.chunk(qkv, chunks=3, dim=-1)

        Q = Q.reshape(B, T, self.heads, self.head_dim)
        K = K.reshape(B, T, self.heads, self.head_dim)
        V = V.reshape(B, T, self.heads, self.head_dim)

        Q = Q.transpose(1, 2)
        K = K.transpose(1, 2)
        V = V.transpose(1, 2)

        # 1. Determine timeline tracking pointers BEFORE updating the cache block
        if past_kv is not None:
            start_pos = past_kv.current_len  # e.g., 3 tokens already exist
            end_pos = start_pos + T           # e.g., 3 + 1 = 4 total tokens
            
            K, V = past_kv.update(K, V)
            total_history_len = K.shape[2]    # will equal end_pos
        else:
            start_pos = 0
            end_pos = T
            total_history_len = T

        scores = Q @ K.transpose(-2, -1)
        scores = scores / (self.head_dim ** 0.5)

        if past_kv is None:
            mask_slice = self.causal_mask[:T, :total_history_len]
        else:
            mask_slice = torch.ones( T,total_history_len,device=x.device)
        
        # Apply mask constraints smoothly
        scores = scores.masked_fill(mask_slice == 0, float("-inf"))

        attention_weights = torch.softmax(scores, dim=-1)
        attention_output = attention_weights @ V

        # Reshape structure back to baseline formats
        attention_output = attention_output.transpose(1, 2)
        attention_output = attention_output.reshape(B, T, C)

        output = self.output_projection(attention_output)

        return output


In [165]:
attention = MultiHeadAttention(
    hidden=8,
    heads=2,
    max_seq_len=16
)

In [166]:
x_prefill = torch.randn(1, 3, 8)

In [167]:
cache = PreallocatedKVCache(
    batch_size=1,
    num_heads=2,
    max_seq_len=16,
    head_dim=4
)

In [168]:
out_prefill = attention(x_prefill, past_kv=cache)

In [169]:
print(out_prefill.shape)
print(cache.current_len)

torch.Size([1, 3, 8])
3


In [170]:
print(
    "Q:", Q.shape,
    "K:", K.shape,
    "V:", V.shape
)

Q: torch.Size([2, 3, 2, 4]) K: torch.Size([1, 2, 6, 4]) V: torch.Size([1, 2, 6, 4])


In [171]:
x_new = torch.randn(1, 1, 8)

out_decode = attention(
    x_new,
    past_kv=cache
)

In [172]:
print(out_decode.shape)
print(cache.current_len)

torch.Size([1, 1, 8])
4


In [173]:
print(
    "Q:", Q.shape,
    "K:", K.shape,
    "V:", V.shape
)

Q: torch.Size([2, 3, 2, 4]) K: torch.Size([1, 2, 6, 4]) V: torch.Size([1, 2, 6, 4])


## experiment

In [174]:
torch.manual_seed(42)

x = torch.randn(1, 4, 8)

In [175]:
full_output = attention(x, past_kv=None)

In [176]:
reference = full_output[:, -1:, :]

In [177]:
cache = PreallocatedKVCache(
    batch_size=1,
    num_heads=2,
    max_seq_len=16,
    head_dim=4
)

In [178]:
prefill_output = attention(
    x[:, :3, :],
    past_kv=cache
)

In [179]:
decode_output = attention(
    x[:, 3:, :],
    past_kv=cache
)

In [180]:
print("reference:", reference.shape)
print("cached:", decode_output.shape)

print(
    "max difference:",
    torch.max(torch.abs(reference - decode_output))
)

reference: torch.Size([1, 1, 8])
cached: torch.Size([1, 1, 8])
max difference: tensor(2.9802e-08, grad_fn=<MaxBackward1>)


In [181]:

import torch
import torch.nn as nn

class GPT2Block(nn.Module):

    def __init__(self, hidden_size, num_heads, max_seq_len):
        super().__init__()

        self.ln1 = MyLayerNorm(hidden_size)

        self.attention = MultiHeadAttention(hidden_size, num_heads, max_seq_len)
  
        self.ln2 = MyLayerNorm(hidden_size)
  
        self.mlp = MLP(hidden_size)

    def forward(self, x,kv_cache = None):
        
        residual = x
        
        x = self.ln1(x)
        x = self.attention(x,past_kv=kv_cache)
        
        x = residual + x

        residual = x
    
        x = self.ln2(x)
        x = self.mlp(x)
        x = residual + x

        return x

In [182]:
cache0 = PreallocatedKVCache(
    batch_size=1,
    num_heads=2,
    max_seq_len=16,
    head_dim=4
)

cache1 = PreallocatedKVCache(
    batch_size=1,
    num_heads=2,
    max_seq_len=16,
    head_dim=4
)

In [183]:
block = GPT2Block(hidden_size=8,num_heads=2,max_seq_len=16)

In [184]:
x = torch.randn(1, 3, 8)

out0 = block(x, kv_cache=cache0)
out1 = block(x, kv_cache=cache1)

In [185]:
print(cache0.current_len)
print(cache1.current_len)

3
3


In [186]:
new_x = torch.randn(1, 1, 8)

out = block(new_x, kv_cache=cache0)

In [187]:
print("cache0:", cache0.current_len)
print("cache1:", cache1.current_len)

cache0: 4
cache1: 3


In [ ]:
class GPT2(nn.Module):

    def __init__(self, vocab_size, hidden_size,
                 num_layers, num_heads, max_seq_len):

        super().__init__()
        # Store architecture details needed for cache creation
        self.num_layers = num_layers
        self.num_heads = num_heads
        self.max_seq_len = max_seq_len
        # GPT-2 standard head dimension is hidden_size // num_heads (e.g., 768 // 12 = 64)
        self.head_dim = hidden_size // num_heads 

        self.embeddings = GPT2Embeddings(vocab_size, hidden_size, max_seq_len)

        self.blocks = nn.ModuleList([
            GPT2Block(hidden_size, num_heads, max_seq_len) 
            for _ in range(num_layers)
        ])

        self.ln_f = MyLayerNorm(hidden_size)

        self.lm_head = nn.Linear(hidden_size, vocab_size, bias=False)
        
        # Initialize kv_caches placeholder as None
        self.kv_caches = None

    def init_kv_cache(self, batch_size):
        """
        Populates self.kv_caches with a unique PreallocatedKVCache 
        instance per transformer block layer.
        """
        self.kv_caches = [
            PreallocatedKVCache(
                batch_size=batch_size,
                num_heads=self.num_heads,
                max_seq_len=self.max_seq_len,
                head_dim=self.head_dim
            )
            for _ in range(self.num_layers)
        ]

        def forward(self, input_ids):

            x = self.embeddings(input_ids)

            for i in range(len(self.blocks)):
                x = self.blocks[i](x, kv_cache=self.kv_caches[i])

            x = self.ln_f(x)

            logits = x @ self.embeddings.token_embedding.weight.T

            return logits



In [ ]:
class GPT2(nn.Module):

    def __init__(self,vocab_size,hidden_size,num_heads,num_layers,max_seq_len):
        super().__init__()

        self.embeddings = GPT2Embeddings(vocab_size,hidden_size,max_seq_len)

        self.blocks = nn.ModuleList([
            GPT2Block(hidden_size,num_heads,max_seq_len)
            for _ in range(num_layers)
        ])

        self.ln_f = MyLayerNorm(hidden_size)

        self.kv_caches = None

    def init_kv_cache(self, batch_size):

        self.kv_caches = [
            PreallocatedKVCache(
                batch_size=batch_size,
                num_heads=self.blocks[0].attention.heads,
                max_seq_len=self.blocks[0].attention.causal_mask.shape[0],
                head_dim=self.blocks[0].attention.head_dim,
            )
            for _ in range(len(self.blocks))
        ]

    def forward(self, input_ids, use_cache=False):

        x = self.embeddings(input_ids)

        for i, block in enumerate(self.blocks):

            if use_cache:
                x = block(
                    x,
                    kv_cache=self.kv_caches[i]
                )
            else:
                x = block(x)

        x = self.ln_f(x)

        logits = (
            x @ self.embeddings.token_embedding.weight.T
        )

        return logits

    def reset_kv_cache(self):
     self.kv_caches = None