In [92]:
import torch

In [93]:
x =torch.arange(24).reshape(2,3,4)

In [94]:
x.shape

torch.Size([2, 3, 4])

In [95]:
x[0]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [96]:
x[1]

tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])

In [97]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [98]:
x[:,1,:]

tensor([[ 4,  5,  6,  7],
        [16, 17, 18, 19]])

In [99]:
x[:, :, 0]

tensor([[ 0,  4,  8],
        [12, 16, 20]])

In [100]:
import torch

x = torch.arange(24).reshape(2, 3, 4)

print(x)
print("shape:", x.shape)
print("dtype:", x.dtype)
print("device:", x.device)
print("numel:", x.numel())
print("element size:", x.element_size())
print("memory:", x.numel() * x.element_size(), "bytes")

print("x[0]:", x[0])
print("x[0].shape:", x[0].shape)

print("x[:, 1, :]:", x[:, 1, :])
print("x[:, 1, :].shape:", x[:, 1, :].shape)

print("x[:, :, 0]:", x[:, :, 0])
print("x[:, :, 0].shape:", x[:, :, 0].shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
shape: torch.Size([2, 3, 4])
dtype: torch.int64
device: cpu
numel: 24
element size: 8
memory: 192 bytes
x[0]: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
x[0].shape: torch.Size([3, 4])
x[:, 1, :]: tensor([[ 4,  5,  6,  7],
        [16, 17, 18, 19]])
x[:, 1, :].shape: torch.Size([2, 4])
x[:, :, 0]: tensor([[ 0,  4,  8],
        [12, 16, 20]])
x[:, :, 0].shape: torch.Size([2, 3])


In [101]:
x = torch.randn(2, 8, 768)
# (batch,sequence_length,hidden_size)


In [102]:
x.shape

torch.Size([2, 8, 768])

In [103]:
x.numel()

12288

In [104]:
x.element_size()

4

In [105]:
x[0].shape

torch.Size([8, 768])

In [106]:
x[:, 0].shape

torch.Size([2, 768])

In [107]:
x[:,:,0].shape

torch.Size([2, 8])

In [108]:
x.reshape(2, 8, 12, 64).shape

torch.Size([2, 8, 12, 64])

In [109]:
y = x.reshape(2, 8, 12, 64)

In [110]:
z = y.transpose(1, 2)

In [111]:
z.shape

torch.Size([2, 12, 8, 64])

In [112]:
import torch

B = 1
H = 2
T = 4
D = 3

Q = torch.randn(B, H, T, D)
K = torch.randn(B, H, T, D)

print("Q:", Q.shape)
print("K:", K.shape)

scores = Q @ K.transpose(-2, -1)

print("K^T:", K.transpose(-2, -1).shape)
print("scores:", scores.shape)

Q: torch.Size([1, 2, 4, 3])
K: torch.Size([1, 2, 4, 3])
K^T: torch.Size([1, 2, 3, 4])
scores: torch.Size([1, 2, 4, 4])


In [113]:
import torch

Q = torch.tensor([[[[1., 2.],
                     [3., 4.]]]])

K = torch.tensor([[[[5., 6.],
                     [7., 8.]]]])

print("Q:", Q)
print("Q shape:", Q.shape)

print("K:", K)
print("K shape:", K.shape)

scores = Q @ K.transpose(-2, -1)

print("scores:", scores)
print("scores shape:", scores.shape)

Q: tensor([[[[1., 2.],
          [3., 4.]]]])
Q shape: torch.Size([1, 1, 2, 2])
K: tensor([[[[5., 6.],
          [7., 8.]]]])
K shape: torch.Size([1, 1, 2, 2])
scores: tensor([[[[17., 23.],
          [39., 53.]]]])
scores shape: torch.Size([1, 1, 2, 2])


In [114]:
scores

tensor([[[[17., 23.],
          [39., 53.]]]])

In [115]:
import torch

Q = torch.tensor([[[[1., 2.],
                     [3., 4.]]]])

K = torch.tensor([[[[5., 6.],
                     [7., 8.]]]])

scores = Q @ K.transpose(-2, -1)

print(scores)

tensor([[[[17., 23.],
          [39., 53.]]]])


In [116]:
import torch

Q = torch.tensor([[[[1., 2.],
                     [3., 4.],
                     [5.,6.]]]])

K = torch.tensor([[[[1., 1.],
                     [2., 2.],
                     [3.,3.]]]])

scores = Q @ K.transpose(-2, -1)

print(scores)

scale = torch.sqrt(torch.tensor(Q.shape[-1], dtype=Q.dtype))
scaled_scores = scores / scale
scaled_scores

tensor([[[[ 3.,  6.,  9.],
          [ 7., 14., 21.],
          [11., 22., 33.]]]])


tensor([[[[ 2.1213,  4.2426,  6.3640],
          [ 4.9497,  9.8995, 14.8492],
          [ 7.7782, 15.5563, 23.3345]]]])

In [117]:
import torch

Q= torch.tensor([[[[1,2],
                   [3,4],
                   [5,6]]]])

K = torch.tensor([[[[1,1],
                    [2,2],
                    [3,3]]]])

score = Q @ K.transpose(-2,-1)

score


scale = torch.sqrt(torch.tensor(Q.shape[-1], dtype=Q.dtype))
scaled_score =score/scale

print("scale:", scale)
print("scaled scores:", scaled_score)


scale: tensor(1.4142)
scaled scores: tensor([[[[ 2.1213,  4.2426,  6.3640],
          [ 4.9497,  9.8995, 14.8492],
          [ 7.7782, 15.5563, 23.3345]]]])


In [118]:
Q.shape

torch.Size([1, 1, 3, 2])

In [119]:
K.shape

torch.Size([1, 1, 3, 2])

In [120]:
score.shape

torch.Size([1, 1, 3, 3])

In [121]:
scores = Q @ K.transpose(1, 2)

RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [3, 2] but got: [3, 1].

In [122]:
mask = torch.tril(torch.ones(3,3))
masked_scores = scaled_scores.masked_fill(mask==0,float("-inf"))

print(masked_scores)

tensor([[[[ 2.1213,    -inf,    -inf],
          [ 4.9497,  9.8995,    -inf],
          [ 7.7782, 15.5563, 23.3345]]]])


In [123]:
import torch

Q= torch.tensor([[[[1,2],
      [3,4],
      [5,6]]]])

K = torch.tensor([[[[1,1],
       [2,2],
       [3,3]]]])

scores = Q @ K.transpose(-2,-1)

scale = torch.sqrt(torch.tensor(Q.shape[-1],dtype=Q.dtype))

scaled_scores =scores/scale

mask =torch.tril(torch.ones(3,3))

masked_scores = scaled_scores.masked_fill(mask ==0,float("-inf"))

mask
masked_scores

tensor([[[[ 2.1213,    -inf,    -inf],
          [ 4.9497,  9.8995,    -inf],
          [ 7.7782, 15.5563, 23.3345]]]])

In [124]:
import torch

Q= torch.tensor([[[[1,2],
      [3,4],
      [5,6]]]])

K = torch.tensor([[[[1,1],
       [2,2],
       [3,3]]]])

scores = Q @ K.transpose(-2,-1)

scale = torch.sqrt(torch.tensor(Q.shape[-1],dtype=Q.dtype))

scaled_scores =scores/scale

mask =torch.tril(torch.ones(3,3))

masked_scores = scaled_scores.masked_fill(mask ==0,float("-inf"))



In [125]:
attention_weights = torch.softmax(masked_scores, dim =-1)

print("attention weights:")
print(attention_weights)


print("row sums:")
print(attention_weights.sum(dim=-1))

attention weights:
tensor([[[[1.0000e+00, 0.0000e+00, 0.0000e+00],
          [7.0353e-03, 9.9296e-01, 0.0000e+00],
          [1.7530e-07, 4.1860e-04, 9.9958e-01]]]])
row sums:
tensor([[[1., 1., 1.]]])


In [126]:
V = torch.tensor([[[[10., 20.],
                     [30., 40.],
                     [50., 60.]]]])


attention_output = attention_weights @ V

print("V shape:", V.shape)
print("attention output:")
print(attention_output)
print("attention output shape:", attention_output.shape)

V shape: torch.Size([1, 1, 3, 2])
attention output:
tensor([[[[10.0000, 20.0000],
          [29.8593, 39.8593],
          [49.9916, 59.9916]]]])
attention output shape: torch.Size([1, 1, 3, 2])


In [127]:
#### Toy Attention
def causal_attention(Q,K,V):

    scores = Q @ K.transpose(-2,-1)

    scale = torch.sqrt(torch.tensor(Q.shape[-1],dtype=Q.dtype))

    scaled_score = scores/scale

    mask = torch.tril(torch.ones(Q.shape[-2],Q.shape[-2]))

    masked_scores = scaled_score.masked_fill(mask ==0,float("-inf"))

    attention_weights = torch.softmax(masked_scores,dim=-1)

    attention_output = attention_weights @ V

    return attention_output ,attention_weights

output, weights = causal_attention(Q, K, V)

print("output:")
print(output)

print("weights:")
print(weights)

print("row sums:")
print(weights.sum(dim=-1))

output:
tensor([[[[10.0000, 20.0000],
          [29.8593, 39.8593],
          [49.9916, 59.9916]]]])
weights:
tensor([[[[1.0000e+00, 0.0000e+00, 0.0000e+00],
          [7.0353e-03, 9.9296e-01, 0.0000e+00],
          [1.7530e-07, 4.1860e-04, 9.9958e-01]]]])
row sums:
tensor([[[1., 1., 1.]]])


In [128]:
linear =torch.nn.Linear(4,6)

linear

Linear(in_features=4, out_features=6, bias=True)

In [129]:
import torch

linear =torch.nn.Linear(4,6)

x =torch.randn(2,3,4)

y =linear(x)

print("x:",x.shape)
print("weight:",linear.weight.shape)
print("bias:", linear.bias.shape)
print("y:", y.shape)


x: torch.Size([2, 3, 4])
weight: torch.Size([6, 4])
bias: torch.Size([6])
y: torch.Size([2, 3, 6])


In [130]:
import torch

B =2
T =3
hidden =8

x = torch.randn(B,T,hidden)

qkv_projection = torch.nn.Linear(hidden,3 * hidden)

qkv =qkv_projection(x)

print("x:",x.shape)
print("qkv:",qkv.shape)

x: torch.Size([2, 3, 8])
qkv: torch.Size([2, 3, 24])


In [131]:
B =2
T=3
hidden =8

x =torch.randn(B,T,hidden)

qkv_projection = torch.nn.Linear(hidden, 3 * hidden)

qkv = qkv_projection(x)

Q,K,V = torch.chunk(qkv,chunks=3,dim=-1)

print(Q.shape,K.shape,V.shape)

torch.Size([2, 3, 8]) torch.Size([2, 3, 8]) torch.Size([2, 3, 8])


In [132]:
hidden =8
heads =2
head_dim =4


Q=Q.reshape(B,T,heads,head_dim)
K=K.reshape(B,T,heads,head_dim)
V=V.reshape(B,T,heads,head_dim)

In [133]:
print((Q.transpose(1,2).shape,K.transpose(1,2).shape,V.transpose(1,2).shape))

(torch.Size([2, 2, 3, 4]), torch.Size([2, 2, 3, 4]), torch.Size([2, 2, 3, 4]))


In [134]:
def causal_attention(Q,K,V,mask):

    scores = Q @ K.transpose(-2,-1)

    scale = torch.sqrt(torch.tensor(Q.shape[-1],dtype=Q.dtype))

    scaled_score = scores/scale

    mask = torch.tril(torch.ones(Q.shape[-2],Q.shape[-2]))

    masked_scores = scaled_score.masked_fill(mask ==0,float("-inf"))

    attention_weights = torch.softmax(masked_scores,dim=-1)

    attention_output = attention_weights @ V

    return attention_output , attention_weights

output= causal_attention(Q, K, V,mask)



In [135]:
output.shape

AttributeError: 'tuple' object has no attribute 'shape'

In [136]:
output.transpose(1,2)

output = output.reshape(B,T,hidden)

print(output.shape)

AttributeError: 'tuple' object has no attribute 'transpose'

In [137]:
attention_output,weights = causal_attention(Q, K, V)

print("attention:", attention_output.shape)

attention_output = attention_output.transpose(1, 2)

print("after transpose:", attention_output.shape)

attention_output = attention_output.reshape(B, T, hidden)

print("after reshape:", attention_output.shape)


TypeError: causal_attention() missing 1 required positional argument: 'mask'

In [138]:
import torch
import torch.nn as nn 

class MultiHeadAttention(nn.Module):

    def __init__(self,hidden,heads,max_seq_len):
        super().__init__()

        self.hidden = hidden
        self.heads = heads
        self.head_dim =hidden //heads

        self.register_buffer("causal_mask",torch.tril(torch.ones(max_seq_len,max_seq_len)))

        self.qkv_projection = nn.Linear(hidden,3 * hidden)
        self.output_projection =nn.Linear(hidden,hidden)



    def forward(self,x):
        B,T,C = x.shape


        qkv =self.qkv_projection(x)

        Q,K,V = torch.chunk(qkv,chunks=3,dim =-1)

        Q =Q.reshape(B,T,self.heads,self.head_dim)
        K =K.reshape(B,T,self.heads,self.head_dim)
        V =V.reshape(B,T,self.heads,self.head_dim)

        Q = Q.transpose(2,1)
        K =K.transpose(2,1)
        V =V.transpose(2,1)

        mask_slice = self.causal_mask[:T, :T]

        attention_output, _ = causal_attention(Q,K,V,mask_slice)

        attention_output =attention_output.transpose(2,1)

        attention_output =attention_output.reshape(B,T,C)

        output =self.output_projection(attention_output)

        return output





In [139]:
attention = MultiHeadAttention(
    hidden=8,
    heads=2
)

x = torch.randn(2, 3, 8)

y = attention(x)

print("x:", x.shape)
print("y:", y.shape)

TypeError: MultiHeadAttention.__init__() missing 1 required positional argument: 'max_seq_len'

In [140]:
print(sum(p.numel() for p in attention.parameters()))

288


In [141]:
attention = MultiHeadAttention(
    hidden=8,
    heads=2,
    max_seq_len=16
)

x = torch.randn(2, 3, 8)

y = attention(x)

print(y.shape)
print(attention.causal_mask.shape)
print(attention.causal_mask.device)

torch.Size([2, 3, 8])
torch.Size([16, 16])
cpu


In [142]:
print(
    "parameters:",
    sum(p.numel() for p in attention.parameters())
)

print(
    "buffers:",
    [(name, buf.shape) for name, buf in attention.named_buffers()]
)

parameters: 288
buffers: [('causal_mask', torch.Size([16, 16]))]


In [143]:
attention = attention.to("cuda")

print(attention.causal_mask.device)

cuda:0


# LayerNorm

In [144]:
x =torch.tensor([2.0,4.,6.,8.])

ln = nn.LayerNorm(4)

y =ln(x)

print("x:",x)
print("y:",y)
print("weight:",ln.weight)
print("bias:",ln.bias)

x: tensor([2., 4., 6., 8.])
y: tensor([-1.3416, -0.4472,  0.4472,  1.3416],
       grad_fn=<NativeLayerNormBackward0>)
weight: Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)
bias: Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)


In [145]:
x = torch.tensor([[2., 4., 6., 8.]])

mean = torch.mean(x)
variance =  torch.var(x)

eps =1e-5
x_norm = (x -mean)/torch.sqrt(variance +eps)

print(mean,variance,x_norm)

tensor(5.) tensor(6.6667) tensor([[-1.1619, -0.3873,  0.3873,  1.1619]])


In [146]:
nn.LayerNorm(4)(x)

tensor([[-1.3416, -0.4472,  0.4472,  1.3416]],
       grad_fn=<NativeLayerNormBackward0>)

In [147]:
import torch
import torch.nn as nn

x = torch.tensor([[2., 4., 6., 8.]])

ln = nn.LayerNorm(4)

print("weight:", ln.weight)
print("bias:", ln.bias)

y = ln(x)

print("y:", y)

weight: Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)
bias: Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)
y: tensor([[-1.3416, -0.4472,  0.4472,  1.3416]],
       grad_fn=<NativeLayerNormBackward0>)


In [148]:
class MyLayerNorm(nn.Module):

    def __init__(self,hidden_size,eps =1e-5):

        super().__init__()

        self.eps =eps

        self.weight = nn.Parameter(torch.ones(hidden_size))

        self.bias =nn.Parameter(torch.zeros(hidden_size))

    def forward(self, x):

        mean = torch.mean(x, dim=-1, keepdim=True)

        variance = torch.mean((x - mean) ** 2, dim=-1, keepdim=True)

        x_norm = (x - mean) / torch.sqrt(variance + self.eps)

        return x_norm * self.weight + self.bias



In [149]:
torch.manual_seed(42)

x = torch.randn(2, 8, 768)

my_ln = MyLayerNorm(768)
torch_ln = nn.LayerNorm(768)

# Make both have exactly the same parameters
torch_ln.weight.data.copy_(my_ln.weight.data)
torch_ln.bias.data.copy_(my_ln.bias.data)

y_my = my_ln(x)
y_torch = torch_ln(x)

print("My shape:", y_my.shape)
print("PyTorch shape:", y_torch.shape)

print("Max difference:", torch.max(torch.abs(y_my - y_torch)))
print("Match:", torch.allclose(y_my, y_torch))

My shape: torch.Size([2, 8, 768])
PyTorch shape: torch.Size([2, 8, 768])
Max difference: tensor(4.7684e-07, grad_fn=<MaxBackward1>)
Match: False


In [177]:
class MLP(nn.Module):
    def __init__(self, hidden_size):
        
        super().__init__()

        self.fc1 = nn.Linear(hidden_size, 4 * hidden_size)
        self.gelu = nn.GELU(approximate="tanh")
        self.fc2 = nn.Linear(4 * hidden_size, hidden_size)

    def forward(self, x):
        x = self.fc1(x)
        x = self.gelu(x)
        x = self.fc2(x)
        return x

In [178]:
x = torch.randn(2, 8, 768)

mlp = MLP(768)

y = mlp(x)

print("input:", x.shape)
print("output:", y.shape)

input: torch.Size([2, 8, 768])
output: torch.Size([2, 8, 768])


In [206]:
import torch
import torch.nn as nn


class MLP(nn.Module):

    def __init__(self, hidden_size):
        super().__init__()

        # 768 → 3072
        self.fc1 = nn.Linear(hidden_size, 4 * hidden_size)

        self.gelu = nn.GELU(approximate="tanh")

        # 3072 → 768
        self.fc2 = nn.Linear(4 * hidden_size, hidden_size)

    def forward(self, x):

        x = self.fc1(x)


        x = self.gelu(x)

        x = self.fc2(x)

        return x


# Test
x = torch.randn(2, 8, 768)

mlp = MLP(768)

y = mlp(x)

print("input:", x.shape)
print("output:", y.shape)

print("fc1 weight:", mlp.fc1.weight.shape)
print("fc2 weight:", mlp.fc2.weight.shape)

print("parameters:",
      sum(p.numel() for p in mlp.parameters()))

input: torch.Size([2, 8, 768])
output: torch.Size([2, 8, 768])
fc1 weight: torch.Size([3072, 768])
fc2 weight: torch.Size([768, 3072])
parameters: 4722432


In [207]:
for name, p in mlp.named_parameters():
    print(name, p.shape, p.numel())

print("total:", sum(p.numel() for p in mlp.parameters()))

fc1.weight torch.Size([3072, 768]) 2359296
fc1.bias torch.Size([3072]) 3072
fc2.weight torch.Size([768, 3072]) 2359296
fc2.bias torch.Size([768]) 768
total: 4722432


In [208]:
import torch
import torch.nn as nn

class GPT2Block(nn.Module):

    def __init__(self, hidden_size, num_heads, max_seq_len):
        super().__init__()

        self.ln1 = MyLayerNorm(hidden_size)

        self.attention = MultiHeadAttention(hidden_size, num_heads, max_seq_len)
  
        self.ln2 = MyLayerNorm(hidden_size)
  
        self.mlp = MLP(hidden_size)

    def forward(self, x):
        
        residual = x
        
        x = self.ln1(x)
        x = self.attention(x)
        
        x = residual + x

        residual = x
    
        x = self.ln2(x)
        x = self.mlp(x)
        x = residual + x

        return x


In [209]:
x = torch.randn(2, 8, 768)

block = GPT2Block(
    hidden_size=768,
    num_heads=12,
    max_seq_len=16
)

y = block(x)

print("input:", x.shape)
print("output:", y.shape)
print("input mean:", x.mean().item())
print("output mean:", y.mean().item())
print("input std:", x.std().item())
print("output std:", y.std().item())

input: torch.Size([2, 8, 768])
output: torch.Size([2, 8, 768])
input mean: -0.0047806440852582455
output mean: -0.0003664692339953035
input std: 0.9953237175941467
output std: 1.0389033555984497


# EMbeddings

In [210]:
input_ids =torch.tensor([15496,995,0])

In [211]:
class GPT2Embeddings(nn.Module):

    def __init__(self, vocab_size, hidden_size, max_seq_len):
        super().__init__()

        self.token_embedding = nn.Embedding(vocab_size,hidden_size)

        self.position_embedding = nn.Embedding(max_seq_len,hidden_size)

    def forward(self, input_ids):

        # input_ids [B,T] 

        token_emb = self.token_embedding(input_ids)

        # Create positions 0,1,2,...,T-1

        positions = torch.arange(0,input_ids.shape[-1],device=input_ids.device)
        

        position_emb = self.position_embedding(positions)

        return token_emb + position_emb

In [212]:
positions.shape

NameError: name 'positions' is not defined

In [213]:
emb = GPT2Embeddings(
    vocab_size=50257,
    hidden_size=768,
    max_seq_len=1024
)

input_ids = torch.tensor([
    [15496, 995, 0, 42]
])

x = emb(input_ids)

print(x.shape)


torch.Size([1, 4, 768])


                 input_ids [B,T]
                       │
                       ▼
                GPT2Embeddings
                       │
                       ▼
                   [B,T,768]
                       │
             ┌─────────▼─────────┐
             │                   │
             ▼                   │
          Block 1                │
             │                   │
             ▼                   │
          Block 2                │
             │                   │
            ...                  │
             │                   │
             ▼                   │
         Block 12                │
             │                   │
             ▼                   │
         LayerNorm               │
             │                   │
             ▼                   │
          [B,T,768]              │
             │                   │
             ▼                   │
       Linear → 50257            │
             │                   │
             ▼                   │
       logits [B,T,50257] ◄──────┘

In [214]:
class GPT2(nn.Module):

    def __init__(self, vocab_size, hidden_size,
                 num_layers, num_heads, max_seq_len):

        super().__init__()

        self.embeddings = GPT2Embeddings(vocab_size,hidden_size,max_seq_len)

        self.blocks = nn.ModuleList([
            GPT2Block(hidden_size, num_heads, max_seq_len) 
            for _ in range(num_layers)
        ])

        self.ln_f = MyLayerNorm(hidden_size)

        self.lm_head = nn.Linear(hidden_size,vocab_size,bias=False)

    def forward(self, input_ids):

        x = self.embeddings(input_ids)


        for block in self.blocks:
            x = block(x)

        x = self.ln_f(x)

        logits = x @ self.embeddings.token_embedding.weight.T

        return logits

In [215]:
model = GPT2(
    vocab_size=50257,
    hidden_size=768,
    num_layers=12,
    num_heads=12,
    max_seq_len=1024
)

input_ids = torch.tensor([
    [15496, 995, 0, 42]
])

logits = model(input_ids)

print("input:", input_ids.shape)
print("logits:", logits.shape)
print("parameters:", sum(p.numel() for p in model.parameters()))

input: torch.Size([1, 4])
logits: torch.Size([1, 4, 50257])
parameters: 163037184


In [216]:
class GPT2(nn.Module):

    def __init__(self, vocab_size, hidden_size,
                 num_layers, num_heads, max_seq_len):

        super().__init__()

        self.embeddings = GPT2Embeddings(vocab_size,hidden_size,max_seq_len)

        self.blocks = nn.ModuleList([
            GPT2Block(hidden_size, num_heads, max_seq_len) 
            for _ in range(num_layers)
        ])

        self.ln_f = MyLayerNorm(hidden_size)


    def forward(self, input_ids):

        x = self.embeddings(input_ids)


        for block in self.blocks:
            x = block(x)

        x = self.ln_f(x)

        logits = x @ self.embeddings.token_embedding.weight.T

        return logits

In [217]:
model = GPT2(
    vocab_size=50257,
    hidden_size=768,
    num_layers=12,
    num_heads=12,
    max_seq_len=1024
)

input_ids = torch.tensor([
    [15496, 995, 0, 42]
])

logits = model(input_ids)

print("input:", input_ids.shape)
print("logits:", logits.shape)
print("parameters:", sum(p.numel() for p in model.parameters()))

input: torch.Size([1, 4])
logits: torch.Size([1, 4, 50257])
parameters: 124439808


__init__

    embeddings
        ↓
    GPT2Embeddings(...)

    blocks
        ↓
    ModuleList
        ├── GPT2Block
        ├── GPT2Block
        ├── GPT2Block
        ├── ...
        └── GPT2Block

    final LayerNorm
        ↓
    MyLayerNorm(...)

    language model head
        ↓
    Linear(768 → vocab_size)

input_ids
    ↓
embeddings
    ↓
for each block:
    x = block(x)
    ↓
final LayerNorm
    ↓
lm_head
    ↓
logits

In [218]:
print(sum(p.numel() for p in model.parameters()))

124439808


input_ids
[B,T]
  │
  ▼
Token + Position Embeddings
  │
  ▼
[B,T,768]
  │
  ▼
Block 1
  │
  ▼
Block 2
  │
 ...
  │
  ▼
Block 12
  │
  ▼
Final LayerNorm
  │
  ▼
[B,T,768]
  │
  ▼
LM Head
  │
  ▼
[B,T,50257]

In [219]:
print(model.embeddings.token_embedding.weight.shape)
print(model.embeddings.position_embedding.weight.shape)

for i, block in enumerate(model.blocks):
    print(
        i,
        block.ln1.weight.shape,
        block.attention.qkv_projection.weight.shape,
        block.attention.output_projection.weight.shape,
        block.ln2.weight.shape,
        block.mlp.fc1.weight.shape,
        block.mlp.fc2.weight.shape,
    )

print(model.ln_f.weight.shape)

torch.Size([50257, 768])
torch.Size([1024, 768])
0 torch.Size([768]) torch.Size([2304, 768]) torch.Size([768, 768]) torch.Size([768]) torch.Size([3072, 768]) torch.Size([768, 3072])
1 torch.Size([768]) torch.Size([2304, 768]) torch.Size([768, 768]) torch.Size([768]) torch.Size([3072, 768]) torch.Size([768, 3072])
2 torch.Size([768]) torch.Size([2304, 768]) torch.Size([768, 768]) torch.Size([768]) torch.Size([3072, 768]) torch.Size([768, 3072])
3 torch.Size([768]) torch.Size([2304, 768]) torch.Size([768, 768]) torch.Size([768]) torch.Size([3072, 768]) torch.Size([768, 3072])
4 torch.Size([768]) torch.Size([2304, 768]) torch.Size([768, 768]) torch.Size([768]) torch.Size([3072, 768]) torch.Size([768, 3072])
5 torch.Size([768]) torch.Size([2304, 768]) torch.Size([768, 768]) torch.Size([768]) torch.Size([3072, 768]) torch.Size([768, 3072])
6 torch.Size([768]) torch.Size([2304, 768]) torch.Size([768, 768]) torch.Size([768]) torch.Size([3072, 768]) torch.Size([768, 3072])
7 torch.Size([768]) 

# Comparison Between our GPT and HF's GPT 

In [220]:
import torch
from transformers import GPT2LMHeadModel, GPT2Tokenizer

hf_model = GPT2LMHeadModel.from_pretrained("gpt2")
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

hf_model.eval()

Loading weights: 100%|██████████| 148/148 [00:00<00:00, 16528.84it/s]


GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [221]:
for name, param in hf_model.transformer.h[0].named_parameters():
    print(name, param.shape)

ln_1.weight torch.Size([768])
ln_1.bias torch.Size([768])
attn.c_attn.weight torch.Size([768, 2304])
attn.c_attn.bias torch.Size([2304])
attn.c_proj.weight torch.Size([768, 768])
attn.c_proj.bias torch.Size([768])
ln_2.weight torch.Size([768])
ln_2.bias torch.Size([768])
mlp.c_fc.weight torch.Size([768, 3072])
mlp.c_fc.bias torch.Size([3072])
mlp.c_proj.weight torch.Size([3072, 768])
mlp.c_proj.bias torch.Size([768])


In [222]:
@torch.no_grad()
def load_gpt2_weights(custom_model, hf_model):

    # embeddings
    custom_model.embeddings.token_embedding.weight.copy_(
        hf_model.transformer.wte.weight
    )

    custom_model.embeddings.position_embedding.weight.copy_(
        hf_model.transformer.wpe.weight
    )

    # transformer blocks
    for custom_block, hf_block in zip(
        custom_model.blocks,
        hf_model.transformer.h
    ):
        # LayerNorm 1
        custom_block.ln1.weight.copy_(hf_block.ln_1.weight)
        custom_block.ln1.bias.copy_(hf_block.ln_1.bias)

        # Attention QKV
        custom_block.attention.qkv_projection.weight.copy_(
            hf_block.attn.c_attn.weight.T
        )
        custom_block.attention.qkv_projection.bias.copy_(
            hf_block.attn.c_attn.bias
        )

        # Attention output projection
        custom_block.attention.output_projection.weight.copy_(
            hf_block.attn.c_proj.weight.T
        )
        custom_block.attention.output_projection.bias.copy_(
            hf_block.attn.c_proj.bias
        )

        # LayerNorm 2
        custom_block.ln2.weight.copy_(hf_block.ln_2.weight)
        custom_block.ln2.bias.copy_(hf_block.ln_2.bias)

        # MLP
        custom_block.mlp.fc1.weight.copy_(
            hf_block.mlp.c_fc.weight.T
        )
        custom_block.mlp.fc1.bias.copy_(
            hf_block.mlp.c_fc.bias
        )

        custom_block.mlp.fc2.weight.copy_(
            hf_block.mlp.c_proj.weight.T
        )
        custom_block.mlp.fc2.bias.copy_(
            hf_block.mlp.c_proj.bias
        )

    # final LayerNorm
    custom_model.ln_f.weight.copy_(
        hf_model.transformer.ln_f.weight
    )
    custom_model.ln_f.bias.copy_(
        hf_model.transformer.ln_f.bias
    )

In [223]:
custom_model = GPT2(
    vocab_size=50257,
    hidden_size=768,
    num_layers=12,
    num_heads=12,
    max_seq_len=1024,
)

custom_model.eval()

load_gpt2_weights(custom_model, hf_model)

In [224]:
text = "The future of AI inference is"

inputs = tokenizer(text, return_tensors="pt")

input_ids = inputs["input_ids"]

print(input_ids.shape)
print(input_ids)

torch.Size([1, 6])
tensor([[  464,  2003,   286,  9552, 32278,   318]])


In [225]:
with torch.no_grad():
    hf_logits = hf_model(input_ids).logits
    custom_logits = custom_model(input_ids)

print(hf_logits.shape)
print(custom_logits.shape)

torch.Size([1, 6, 50257])
torch.Size([1, 6, 50257])


In [226]:
print(torch.allclose(
    hf_logits,
    custom_logits,
    atol=1e-4,
    rtol=1e-4
))

True


In [227]:
max_diff = torch.max(
    torch.abs(hf_logits - custom_logits)
)

print("max difference:", max_diff.item())

max difference: 6.103515625e-05


In [228]:
hf_next_token = torch.argmax(hf_logits[:, -1, :], dim=-1)
custom_next_token = torch.argmax(custom_logits[:, -1, :], dim=-1)

print("HF:", hf_next_token)
print("Custom:", custom_next_token)

print(
    "same token:",
    torch.equal(hf_next_token, custom_next_token)
)

HF: tensor([8627])
Custom: tensor([8627])
same token: True


In [229]:
hf_outputs = {}
custom_outputs = {}

def save_output(storage, name):
    def hook(module, inputs, output):
        hf_or_custom_output = output[0] if isinstance(output, tuple) else output
        storage[name] = hf_or_custom_output.detach()
    return hook

handles = []

for i in range(12):
    handles.append(
        hf_model.transformer.h[i].register_forward_hook(
            save_output(hf_outputs, f"block_{i}")
        )
    )

    handles.append(
        custom_model.blocks[i].register_forward_hook(
            save_output(custom_outputs, f"block_{i}")
        )
    )

with torch.no_grad():
    hf_logits = hf_model(input_ids).logits
    custom_logits = custom_model(input_ids)

for handle in handles:
    handle.remove()

for i in range(12):
    diff = (
        hf_outputs[f"block_{i}"]
        - custom_outputs[f"block_{i}"]
    ).abs().max().item()

    print(f"Block {i:2d}: max diff = {diff:.8f}")

print(
    "Final logits:",
    (hf_logits - custom_logits).abs().max().item()
)

Block  0: max diff = 0.00003433
Block  1: max diff = 0.00012207
Block  2: max diff = 0.00006104
Block  3: max diff = 0.00006104
Block  4: max diff = 0.00006104
Block  5: max diff = 0.00006104
Block  6: max diff = 0.00006104
Block  7: max diff = 0.00006104
Block  8: max diff = 0.00006104
Block  9: max diff = 0.00006104
Block 10: max diff = 0.00006866
Block 11: max diff = 0.00024414
Final logits: 6.103515625e-05


In [230]:
hf_model.eval()
custom_model.eval()

GPT2(
  (embeddings): GPT2Embeddings(
    (token_embedding): Embedding(50257, 768)
    (position_embedding): Embedding(1024, 768)
  )
  (blocks): ModuleList(
    (0-11): 12 x GPT2Block(
      (ln1): MyLayerNorm()
      (attention): MultiHeadAttention(
        (qkv_projection): Linear(in_features=768, out_features=2304, bias=True)
        (output_projection): Linear(in_features=768, out_features=768, bias=True)
      )
      (ln2): MyLayerNorm()
      (mlp): MLP(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (gelu): GELU(approximate='tanh')
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
      )
    )
  )
  (ln_f): MyLayerNorm()
)

In [231]:
with torch.no_grad():
    hf_logits = hf_model(input_ids).logits
    custom_logits = custom_model(input_ids)

print(torch.allclose(
    hf_logits,
    custom_logits,
    atol=1e-4,
    rtol=1e-4
))

print(
    "max difference:",
    (hf_logits - custom_logits).abs().max().item()
)

True
max difference: 6.103515625e-05
