In [1]:
import torch


k_cache =None
v_cache =None


In [2]:
k =torch.tensor([[1.,2.]])
v =torch.tensor([[10.,20.]])


In [3]:
k.shape

torch.Size([1, 2])

In [4]:
if k_cache is None:
    k_cache = k
    v_cache = v

In [5]:
print(k_cache)
print(v_cache)

tensor([[1., 2.]])
tensor([[10., 20.]])


In [6]:
k = torch.tensor([[3., 4.]])
v = torch.tensor([[30., 40.]])

In [7]:
k_cache =torch.cat([k_cache,k],dim=0)
v_cache =torch.cat([v_cache,v],dim=0)

In [8]:
print(k_cache)
print(v_cache)

tensor([[1., 2.],
        [3., 4.]])
tensor([[10., 20.],
        [30., 40.]])


In [9]:
k = torch.tensor([[5., 6.]])
v = torch.tensor([[50., 60.]])

In [10]:
k_cache = torch.cat([k_cache, k], dim=0)
v_cache = torch.cat([v_cache, v], dim=0)

In [11]:
q = torch.tensor([[7., 8.]])

In [12]:
keys = k_cache
values = v_cache

In [13]:
k_new = torch.tensor([[7., 8.]])
v_new = torch.tensor([[70., 80.]])


In [14]:
print(k_cache)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [15]:
class KVCache:

    def __init__(self):
        self.k =None
        self.v =None

    def append(self,new_k,new_v):

        if self.k is None:
            self.k =new_k
            self.v =new_v
        else:
            self.k =torch.cat([self.k,new_k],dim=0)
            self.v =torch.cat([self.v,new_v],dim=0)

    def get(self):
        return self.k,self.v

In [16]:
cache =KVCache()

In [17]:
cache.append(
    torch.tensor([[1., 2.]]),
    torch.tensor([[10., 20.]])
)

In [18]:
print(cache.get())

(tensor([[1., 2.]]), tensor([[10., 20.]]))


In [19]:
cache.append(
    torch.tensor([[3., 4.]]),
    torch.tensor([[30., 40.]])
)

In [20]:
cache.append(
    torch.tensor([[5., 6.]]),
    torch.tensor([[50., 60.]])
)

In [21]:
keys, values = cache.get()

In [22]:
class KVCCache:

    def __init__(self):
        self.k =None
        self.v =None

    def append(self,New_k,New_v):

        if self.k is None:
            self.k = New_k
            self.v =New_v
        else:
            self.k=torch.cat([self.k,New_k],dim=2)
            self.v =torch.cat([self.v,New_v],dim=2)

    def get(self):
        return self.k,self.v
    

In [23]:
K_A = torch.tensor([[1., 2.]])
V_A = torch.tensor([[10., 20.]])

In [24]:
kv= KVCCache()


In [25]:
kv.append(K_A,V_A)

In [26]:
print(kv.get())

(tensor([[1., 2.]]), tensor([[10., 20.]]))


In [27]:
K_B = torch.tensor([[3., 4.]])
V_B = torch.tensor([[30., 40.]])

K_C = torch.tensor([[5., 6.]])
V_C = torch.tensor([[50., 60.]])

In [28]:
kv.append(K_B,V_B)
kv.append(K_C,V_C)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [ ]:
print(kv.get())

(tensor([[1., 2.]]), tensor([[10., 20.]]))


In [ ]:
cache = KVCCache()

K_A = torch.randn(1, 2, 1, 4)
V_A = torch.randn(1, 2, 1, 4)

K_B = torch.randn(1, 2, 1, 4)
V_B = torch.randn(1, 2, 1, 4)

K_C = torch.randn(1, 2, 1, 4)
V_C = torch.randn(1, 2, 1, 4)

cache.append(K_A, V_A)
cache.append(K_B, V_B)
cache.append(K_C, V_C)

K, V = cache.get()

print("K:", K.shape)
print("V:", V.shape)

K: torch.Size([1, 2, 3, 4])
V: torch.Size([1, 2, 3, 4])


In [ ]:
print(K)

tensor([[[[ 0.6273, -1.2644,  0.3827, -1.6724],
          [-0.2134,  0.4255,  1.1662,  0.5214],
          [-1.2634,  1.0145,  1.3764, -1.0006]],

         [[ 0.4027,  0.4313,  1.5817, -0.6784],
          [-0.4958, -0.1106, -1.9495, -0.6949],
          [ 1.7570, -0.5134,  0.2265, -1.6640]]]])


In [ ]:
Q_D = torch.tensor([[[[1., 0., 1., 0.]],
                     [[0., 1., 0., 1.]]]])

In [ ]:
K_cache, V_cache = cache.get()

In [ ]:
scores = Q_D @ K_cache.transpose(-2, -1)

In [ ]:
print(scores.shape)

torch.Size([1, 2, 1, 3])


In [ ]:
scores =scores/(4 ** 0.5)

In [ ]:
weights = torch.softmax(scores, dim=-1)

In [ ]:
output = weights @ V_cache

In [ ]:
scores.shape

torch.Size([1, 2, 1, 3])

In [ ]:
weights

tensor([[[[0.3831, 0.3723, 0.2446]],

         [[0.4679, 0.3539, 0.1782]]]])

In [168]:
output.shape

torch.Size([1, 2, 1, 4])

```text
PROMPT
A B C
 │
 ▼
Compute K,V
 │
 ▼
STORE
 │
 ▼
┌─────────────┐
│ KV CACHE    │
│ K: A B C    │
│ V: A B C    │
└──────┬──────┘
       │
       │ new token D
       ▼
      Q_D
       │
       ├──────────────► K cache
       │                    │
       │                    ▼
       │               Q_D × Kᵀ
       │                    │
       │                    ▼
       │                 softmax
       │                    │
       │                    ▼
       └──────────────► V cache
                            │
                            ▼
                         output